//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Ava.Frontend.Generated/DianaScript.g4 by ANTLR 4.9

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Ava.Frontend {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IDianaScriptListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class DianaScriptBaseListener : IDianaScriptListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="DianaScriptParser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStmt([NotNull] DianaScriptParser.StmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DianaScriptParser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStmt([NotNull] DianaScriptParser.StmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DianaScriptParser.gen__filter_option__NEWLINE"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGen__filter_option__NEWLINE([NotNull] DianaScriptParser.Gen__filter_option__NEWLINEContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DianaScriptParser.gen__filter_option__NEWLINE"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGen__filter_option__NEWLINE([NotNull] DianaScriptParser.Gen__filter_option__NEWLINEContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DianaScriptParser.option"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOption([NotNull] DianaScriptParser.OptionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DianaScriptParser.option"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOption([NotNull] DianaScriptParser.OptionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DianaScriptParser.gen__nullable_gen__seplist__L44__expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGen__nullable_gen__seplist__L44__expr([NotNull] DianaScriptParser.Gen__nullable_gen__seplist__L44__exprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DianaScriptParser.gen__nullable_gen__seplist__L44__expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGen__nullable_gen__seplist__L44__expr([NotNull] DianaScriptParser.Gen__nullable_gen__seplist__L44__exprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DianaScriptParser.gen__seplist__L44__expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGen__seplist__L44__expr([NotNull] DianaScriptParser.Gen__seplist__L44__exprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DianaScriptParser.gen__seplist__L44__expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGen__seplist__L44__expr([NotNull] DianaScriptParser.Gen__seplist__L44__exprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DianaScriptParser.atom"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAtom([NotNull] DianaScriptParser.AtomContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DianaScriptParser.atom"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAtom([NotNull] DianaScriptParser.AtomContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DianaScriptParser.gen__line_wrap_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGen__line_wrap_expr([NotNull] DianaScriptParser.Gen__line_wrap_exprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DianaScriptParser.gen__line_wrap_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGen__line_wrap_expr([NotNull] DianaScriptParser.Gen__line_wrap_exprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DianaScriptParser.gen__optional_NEWLINE"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGen__optional_NEWLINE([NotNull] DianaScriptParser.Gen__optional_NEWLINEContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DianaScriptParser.gen__optional_NEWLINE"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGen__optional_NEWLINE([NotNull] DianaScriptParser.Gen__optional_NEWLINEContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DianaScriptParser.gen__nullable_gen__seplist__L44__name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGen__nullable_gen__seplist__L44__name([NotNull] DianaScriptParser.Gen__nullable_gen__seplist__L44__nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DianaScriptParser.gen__nullable_gen__seplist__L44__name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGen__nullable_gen__seplist__L44__name([NotNull] DianaScriptParser.Gen__nullable_gen__seplist__L44__nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DianaScriptParser.gen__seplist__L44__name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGen__seplist__L44__name([NotNull] DianaScriptParser.Gen__seplist__L44__nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DianaScriptParser.gen__seplist__L44__name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGen__seplist__L44__name([NotNull] DianaScriptParser.Gen__seplist__L44__nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DianaScriptParser.gen__optional_gen__blockOf_else"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGen__optional_gen__blockOf_else([NotNull] DianaScriptParser.Gen__optional_gen__blockOf_elseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DianaScriptParser.gen__optional_gen__blockOf_else"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGen__optional_gen__blockOf_else([NotNull] DianaScriptParser.Gen__optional_gen__blockOf_elseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DianaScriptParser.gen__blockOf_else"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGen__blockOf_else([NotNull] DianaScriptParser.Gen__blockOf_elseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DianaScriptParser.gen__blockOf_else"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGen__blockOf_else([NotNull] DianaScriptParser.Gen__blockOf_elseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DianaScriptParser.gen__nullable_gen__list_gen__snd_elif__elifBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGen__nullable_gen__list_gen__snd_elif__elifBlock([NotNull] DianaScriptParser.Gen__nullable_gen__list_gen__snd_elif__elifBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DianaScriptParser.gen__nullable_gen__list_gen__snd_elif__elifBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGen__nullable_gen__list_gen__snd_elif__elifBlock([NotNull] DianaScriptParser.Gen__nullable_gen__list_gen__snd_elif__elifBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DianaScriptParser.gen__list_gen__snd_elif__elifBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGen__list_gen__snd_elif__elifBlock([NotNull] DianaScriptParser.Gen__list_gen__snd_elif__elifBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DianaScriptParser.gen__list_gen__snd_elif__elifBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGen__list_gen__snd_elif__elifBlock([NotNull] DianaScriptParser.Gen__list_gen__snd_elif__elifBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DianaScriptParser.gen__snd_elif__elifBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGen__snd_elif__elifBlock([NotNull] DianaScriptParser.Gen__snd_elif__elifBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DianaScriptParser.gen__snd_elif__elifBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGen__snd_elif__elifBlock([NotNull] DianaScriptParser.Gen__snd_elif__elifBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DianaScriptParser.gen__closelist__L44__pair"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGen__closelist__L44__pair([NotNull] DianaScriptParser.Gen__closelist__L44__pairContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DianaScriptParser.gen__closelist__L44__pair"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGen__closelist__L44__pair([NotNull] DianaScriptParser.Gen__closelist__L44__pairContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DianaScriptParser.gen___closelist__L44__pair"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGen___closelist__L44__pair([NotNull] DianaScriptParser.Gen___closelist__L44__pairContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DianaScriptParser.gen___closelist__L44__pair"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGen___closelist__L44__pair([NotNull] DianaScriptParser.Gen___closelist__L44__pairContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DianaScriptParser.gen__closelist__L44__expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGen__closelist__L44__expr([NotNull] DianaScriptParser.Gen__closelist__L44__exprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DianaScriptParser.gen__closelist__L44__expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGen__closelist__L44__expr([NotNull] DianaScriptParser.Gen__closelist__L44__exprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DianaScriptParser.gen___closelist__L44__expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGen___closelist__L44__expr([NotNull] DianaScriptParser.Gen___closelist__L44__exprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DianaScriptParser.gen___closelist__L44__expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGen___closelist__L44__expr([NotNull] DianaScriptParser.Gen___closelist__L44__exprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DianaScriptParser.pair"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPair([NotNull] DianaScriptParser.PairContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DianaScriptParser.pair"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPair([NotNull] DianaScriptParser.PairContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DianaScriptParser.gen__line_wrap__L58"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGen__line_wrap__L58([NotNull] DianaScriptParser.Gen__line_wrap__L58Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DianaScriptParser.gen__line_wrap__L58"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGen__line_wrap__L58([NotNull] DianaScriptParser.Gen__line_wrap__L58Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DianaScriptParser.trailer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTrailer([NotNull] DianaScriptParser.TrailerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DianaScriptParser.trailer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTrailer([NotNull] DianaScriptParser.TrailerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DianaScriptParser.bin"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBin([NotNull] DianaScriptParser.BinContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DianaScriptParser.bin"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBin([NotNull] DianaScriptParser.BinContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DianaScriptParser.binseq"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBinseq([NotNull] DianaScriptParser.BinseqContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DianaScriptParser.binseq"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBinseq([NotNull] DianaScriptParser.BinseqContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DianaScriptParser.ibin"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIbin([NotNull] DianaScriptParser.IbinContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DianaScriptParser.ibin"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIbin([NotNull] DianaScriptParser.IbinContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DianaScriptParser.ibinop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIbinop([NotNull] DianaScriptParser.IbinopContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DianaScriptParser.ibinop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIbinop([NotNull] DianaScriptParser.IbinopContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DianaScriptParser.binop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBinop([NotNull] DianaScriptParser.BinopContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DianaScriptParser.binop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBinop([NotNull] DianaScriptParser.BinopContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DianaScriptParser.not"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNot([NotNull] DianaScriptParser.NotContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DianaScriptParser.not"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNot([NotNull] DianaScriptParser.NotContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DianaScriptParser.and_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAnd_expr([NotNull] DianaScriptParser.And_exprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DianaScriptParser.and_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAnd_expr([NotNull] DianaScriptParser.And_exprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DianaScriptParser.or_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOr_expr([NotNull] DianaScriptParser.Or_exprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DianaScriptParser.or_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOr_expr([NotNull] DianaScriptParser.Or_exprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DianaScriptParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpr([NotNull] DianaScriptParser.ExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DianaScriptParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpr([NotNull] DianaScriptParser.ExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DianaScriptParser.gen__seplist_gen__line_wrap__L124_L62__or_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGen__seplist_gen__line_wrap__L124_L62__or_expr([NotNull] DianaScriptParser.Gen__seplist_gen__line_wrap__L124_L62__or_exprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DianaScriptParser.gen__seplist_gen__line_wrap__L124_L62__or_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGen__seplist_gen__line_wrap__L124_L62__or_expr([NotNull] DianaScriptParser.Gen__seplist_gen__line_wrap__L124_L62__or_exprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DianaScriptParser.gen__line_wrap__L124_L62"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGen__line_wrap__L124_L62([NotNull] DianaScriptParser.Gen__line_wrap__L124_L62Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DianaScriptParser.gen__line_wrap__L124_L62"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGen__line_wrap__L124_L62([NotNull] DianaScriptParser.Gen__line_wrap__L124_L62Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DianaScriptParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlock([NotNull] DianaScriptParser.BlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DianaScriptParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlock([NotNull] DianaScriptParser.BlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DianaScriptParser.gen__filter_stmt__gen__or___L59__NEWLINE"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGen__filter_stmt__gen__or___L59__NEWLINE([NotNull] DianaScriptParser.Gen__filter_stmt__gen__or___L59__NEWLINEContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DianaScriptParser.gen__filter_stmt__gen__or___L59__NEWLINE"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGen__filter_stmt__gen__or___L59__NEWLINE([NotNull] DianaScriptParser.Gen__filter_stmt__gen__or___L59__NEWLINEContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DianaScriptParser.gen__or___L59__NEWLINE"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGen__or___L59__NEWLINE([NotNull] DianaScriptParser.Gen__or___L59__NEWLINEContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DianaScriptParser.gen__or___L59__NEWLINE"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGen__or___L59__NEWLINE([NotNull] DianaScriptParser.Gen__or___L59__NEWLINEContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DianaScriptParser.lhs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLhs([NotNull] DianaScriptParser.LhsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DianaScriptParser.lhs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLhs([NotNull] DianaScriptParser.LhsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DianaScriptParser.do"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDo([NotNull] DianaScriptParser.DoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DianaScriptParser.do"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDo([NotNull] DianaScriptParser.DoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DianaScriptParser.then"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterThen([NotNull] DianaScriptParser.ThenContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DianaScriptParser.then"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitThen([NotNull] DianaScriptParser.ThenContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DianaScriptParser.gen__blockOf_do"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGen__blockOf_do([NotNull] DianaScriptParser.Gen__blockOf_doContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DianaScriptParser.gen__blockOf_do"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGen__blockOf_do([NotNull] DianaScriptParser.Gen__blockOf_doContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DianaScriptParser.name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterName([NotNull] DianaScriptParser.NameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DianaScriptParser.name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitName([NotNull] DianaScriptParser.NameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DianaScriptParser.elifBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElifBlock([NotNull] DianaScriptParser.ElifBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DianaScriptParser.elifBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElifBlock([NotNull] DianaScriptParser.ElifBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DianaScriptParser.gen__blockOf_then"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGen__blockOf_then([NotNull] DianaScriptParser.Gen__blockOf_thenContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DianaScriptParser.gen__blockOf_then"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGen__blockOf_then([NotNull] DianaScriptParser.Gen__blockOf_thenContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DianaScriptParser.lhs_seq"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLhs_seq([NotNull] DianaScriptParser.Lhs_seqContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DianaScriptParser.lhs_seq"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLhs_seq([NotNull] DianaScriptParser.Lhs_seqContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DianaScriptParser.start"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStart([NotNull] DianaScriptParser.StartContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DianaScriptParser.start"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStart([NotNull] DianaScriptParser.StartContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DianaScriptParser.gen__nullable_gen__seplist_NEWLINE__stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGen__nullable_gen__seplist_NEWLINE__stmt([NotNull] DianaScriptParser.Gen__nullable_gen__seplist_NEWLINE__stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DianaScriptParser.gen__nullable_gen__seplist_NEWLINE__stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGen__nullable_gen__seplist_NEWLINE__stmt([NotNull] DianaScriptParser.Gen__nullable_gen__seplist_NEWLINE__stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DianaScriptParser.gen__seplist_NEWLINE__stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGen__seplist_NEWLINE__stmt([NotNull] DianaScriptParser.Gen__seplist_NEWLINE__stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DianaScriptParser.gen__seplist_NEWLINE__stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGen__seplist_NEWLINE__stmt([NotNull] DianaScriptParser.Gen__seplist_NEWLINE__stmtContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace Ava.Frontend
